-- GENERATED BY workspace-studio v0.1.0 -- DO NOT EDIT.
--
-- Source of truth: ~/.config/omarchy/workspace-studio.json
-- This file:       ~/.local/state/omarchy/toggles/hypr/zz-workspace-studio.lua
-- Regenerate:      open the bar widget's editor (right-click) and press Apply.
-- Remove:          delete this file and run `hyprctl reload`.
--
-- Loaded last, from ~/.local/state/omarchy/toggles/hypr, by the
-- `require("default.hypr.toggles")` at the end of ~/.config/hypr/hyprland.lua,
-- so the unbinds below reliably win over earlier config.

-- --- workspace rules -------------------------------------------------
hl.workspace_rule({
  workspace = "1",
  on_created_empty = o.launch("chromium --profile-directory='Profile 2'")
})
hl.workspace_rule({ workspace = "2", on_created_empty = o.launch("foot") })
hl.workspace_rule({
  workspace = "3",
  on_created_empty = o.launch("chromium --profile-directory='Profile 2' --app-id=dlijmjnakehgcjngafdkneaigmfcdmhf")
})
hl.workspace_rule({
  workspace = "4",
  on_created_empty = o.launch("chromium --profile-directory='Profile 2' --app=https://app.slack.com/client/T681EDZRV/") .. " & " .. o.launch("chromium --profile-directory='Profile 2' --app=https://web.whatsapp.com/")
})
hl.workspace_rule({
  workspace = "5",
  on_created_empty = o.launch("chromium --profile-directory='Profile 2' --app=https://claude.ai/")
})

-- --- window rules ----------------------------------------------------
hl.window_rule({ name = "wsstudio:ws1:1", match = { class = "chromium" }, workspace = "1" })
hl.window_rule({
  name = "wsstudio:ws2:1",
  match = { class = "(foot|org\\.codeberg\\.dnkl\\.foot)" },
  workspace = "2"
})
hl.window_rule({
  name = "wsstudio:ws3:1",
  match = { class = "chrome-dlijmjnakehgcjngafdkneaigmfcdmhf-Profile_2" },
  workspace = "3"
})
hl.window_rule({
  name = "wsstudio:ws4:1",
  match = { class = "chrome-app\\.slack\\.com__client_T681EDZRV_-Profile_2" },
  workspace = "4"
})
hl.window_rule({
  name = "wsstudio:ws4:2",
  match = { class = "chrome-web\\.whatsapp\\.com__-Profile_2" },
  workspace = "4"
})
hl.window_rule({
  name = "wsstudio:ws5:1",
  match = { class = "chrome-claude\\.ai__-Profile_2" },
  workspace = "5"
})

-- --- workspace binds -------------------------------------------------
-- Keysyms only. Hyprland 0.56.2 silently drops "code:NN" bind keycodes:
-- they land in the bind table with key="" / keycode=0 and match on the
-- modifier mask alone, firing every bind that shares that mask. Both
-- spellings are unbound first so this file is correct either way.

hl.unbind("SUPER + code:10")
hl.unbind("SUPER + 1")
hl.unbind("SUPER + SHIFT + code:10")
hl.unbind("SUPER + SHIFT + 1")
hl.unbind("SUPER + SHIFT + ALT + code:10")
hl.unbind("SUPER + SHIFT + ALT + 1")
o.bind("SUPER + 1", "Switch to workspace 1", hl.dsp.focus({ workspace = "1" }))
o.bind("SUPER + SHIFT + 1", "Move window to workspace 1", hl.dsp.window.move({ workspace = "1" }))
o.bind("SUPER + SHIFT + ALT + 1", "Move window silently to workspace 1", hl.dsp.window.move({ workspace = "1", follow = false }))

hl.unbind("SUPER + code:11")
hl.unbind("SUPER + 2")
hl.unbind("SUPER + SHIFT + code:11")
hl.unbind("SUPER + SHIFT + 2")
hl.unbind("SUPER + SHIFT + ALT + code:11")
hl.unbind("SUPER + SHIFT + ALT + 2")
o.bind("SUPER + 2", "Switch to workspace 2", hl.dsp.focus({ workspace = "2" }))
o.bind("SUPER + SHIFT + 2", "Move window to workspace 2", hl.dsp.window.move({ workspace = "2" }))
o.bind("SUPER + SHIFT + ALT + 2", "Move window silently to workspace 2", hl.dsp.window.move({ workspace = "2", follow = false }))

hl.unbind("SUPER + code:12")
hl.unbind("SUPER + 3")
hl.unbind("SUPER + SHIFT + code:12")
hl.unbind("SUPER + SHIFT + 3")
hl.unbind("SUPER + SHIFT + ALT + code:12")
hl.unbind("SUPER + SHIFT + ALT + 3")
o.bind("SUPER + 3", "Switch to workspace 3", hl.dsp.focus({ workspace = "3" }))
o.bind("SUPER + SHIFT + 3", "Move window to workspace 3", hl.dsp.window.move({ workspace = "3" }))
o.bind("SUPER + SHIFT + ALT + 3", "Move window silently to workspace 3", hl.dsp.window.move({ workspace = "3", follow = false }))

hl.unbind("SUPER + code:13")
hl.unbind("SUPER + 4")
hl.unbind("SUPER + SHIFT + code:13")
hl.unbind("SUPER + SHIFT + 4")
hl.unbind("SUPER + SHIFT + ALT + code:13")
hl.unbind("SUPER + SHIFT + ALT + 4")
o.bind("SUPER + 4", "Switch to workspace 4", hl.dsp.focus({ workspace = "4" }))
o.bind("SUPER + SHIFT + 4", "Move window to workspace 4", hl.dsp.window.move({ workspace = "4" }))
o.bind("SUPER + SHIFT + ALT + 4", "Move window silently to workspace 4", hl.dsp.window.move({ workspace = "4", follow = false }))

hl.unbind("SUPER + code:14")
hl.unbind("SUPER + 5")
hl.unbind("SUPER + SHIFT + code:14")
hl.unbind("SUPER + SHIFT + 5")
hl.unbind("SUPER + SHIFT + ALT + code:14")
hl.unbind("SUPER + SHIFT + ALT + 5")
o.bind("SUPER + 5", "Switch to workspace 5", hl.dsp.focus({ workspace = "5" }))
o.bind("SUPER + SHIFT + 5", "Move window to workspace 5", hl.dsp.window.move({ workspace = "5" }))
o.bind("SUPER + SHIFT + ALT + 5", "Move window silently to workspace 5", hl.dsp.window.move({ workspace = "5", follow = false }))

